name: Deploying
on: 
  push:
    branches: ["main"]

env: 
  FLY_API_TOKEN: ${{ secrets.FLYIO_API_TOKEN}}
  POOL_SIZE: "1"

jobs:
  deploys:
    name: Deploy Fullsatack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      run: flyctl deploy --remote-only
      working-directory: fullstack








